/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SingleStroke {
        /**
          * The image src
         */
        "src": string;
    }
}
declare global {
    interface HTMLSingleStrokeElement extends Components.SingleStroke, HTMLStencilElement {
    }
    var HTMLSingleStrokeElement: {
        prototype: HTMLSingleStrokeElement;
        new (): HTMLSingleStrokeElement;
    };
    interface HTMLElementTagNameMap {
        "single-stroke": HTMLSingleStrokeElement;
    }
}
declare namespace LocalJSX {
    interface SingleStroke {
        /**
          * The image src
         */
        "src"?: string;
    }
    interface IntrinsicElements {
        "single-stroke": SingleStroke;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "single-stroke": LocalJSX.SingleStroke & JSXBase.HTMLAttributes<HTMLSingleStrokeElement>;
        }
    }
}
